[package]
name = "esprit-workflows"
version.workspace = true
edition.workspace = true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvyasingh/Esprit"
homepage = "https://github.com/krtvyasingh/Esprit"
documentation = "https://github.com/krtvyasingh/Esprit"
readme = "README.md"

[dependencies]
anyhow.workspace = true
esprit-agents = { version = "0.1.0", path = "../esprit-agents" }
